Dostosowanie do wymagań, poprawa testowania i uruchamiania algorytmu
N19r4/AlgorithmusPlusBackend pull request #14
Opened 2023-12-19 00:29 UTC by pardonmyfriend

2023-12-19 07:21 UTC, N19r4 approved these changes

2023-12-19 07:21 UTC, N19r4 commented on Backend/TestOptimizationAlgorithm.cs
> +                        var FBest = (double)optimizationAlgorithm.GetType().GetProperty("XBest").GetValue(optimizationAlgorithm);
Proponuję zrobić bardzo prostą funkcję dostępną wszędzie czyli getPropertyValue(func, propertyName) = return func.GetType().getProperty(propertyName).getValue(func)

I ją wywoływać jako np. getPropertyValue(optimizationAlgorithm, "XBest")

Będzie trochę czyściej w kodzie ;)

2023-12-19 07:21 UTC, N19r4 commented on Backend/TestOptimizationAlgorithm.cs
> +                        LiczbaSzukanychParametrów = dim,
A tu czemu nagle polski język wskoczył? :D

2023-12-19 12:28 UTC, irekkosek requested changes

2023-12-19 12:28 UTC, irekkosek commented on Backend/RunAlgorithm.cs
>          static public void Run(string optimizationAlgorithmDLL, string[] testFunctionDLLs, int[] T, int[] N, int dim)
tutaj i w kontrolerze musielibyśmy dostosować jeszcze dane wejściowe

2023-12-28 22:32 UTC, irekkosek approved these changes

2023-12-28 22:33 UTC, merged